// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/Activity.vue')['default']
    GameRoom: typeof import('./src/components/GameRoom.vue')['default']
    GiftMall: typeof import('./src/components/GiftMall.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wfh: typeof import('./src/components/hr/Wfh.vue')['default']
  }
}

export {}
